function [ f, dfdx, dfdu ] = qr_dynamics( x, u, t, user )
%This function calculates the quadrotor's dynamics equations and its
%derivatives

Lr = user.quadrotor_params.length;
m = user.quadrotor_params.mass;
M = user.quadrotor_params.Iy;
g = user.quadrotor_params.gravity_accel;
Kf = user.quadrotor_params.motor_const; 
Ki = user.quadrotor_params.air_const; 
b = user.quadrotor_params.frict_coeff; 

qx = user.idxs.qx;
qy = user.idxs.qy;
qz = user.idxs.qz;
vx = user.idxs.vx;
vy = user.idxs.vy;
vz = user.idxs.vz;
qtheta = user.idxs.qtheta;
qphi = user.idxs.qphi;
qpsi = user.idxs.qpsi;
vtheta = user.idxs.vtheta;
vphi = user.idxs.vphi;
vpsi = user.idxs.vpsi;

T1 = user.idxs.T1; 
T2 = user.idxs.T2; 
T3 = user.idxs.T3; 
T4 = user.idxs.T4; 


f = [ x(vx)                              ; ...
      x(vy)                              ; ...
      x(vz)                              ; ...
      -b/m * x(vx) + (Kf/m)* sin( x(qphi) ) * sum(u)                            ; ...
      -b/m * x(vy) - (Kf/m)* sin( x(qtheta) ) * cos( x(qphi) ) * sum(u)         ; ...
      -g - b/m * x(vz) + (Kf/m)* cos( x(qtheta) ) * cos( x(qphi) ) * sum(u)     ; ...
      x(vtheta) ; ...
      x(vphi)   ; ...
      x(vpsi)   ; ...
      -x(vphi)*x(vpsi) + (Kf*Lr)/M * ( u(T2) - u(T4) )        ; ...
      x(vtheta)*x(vpsi) + (Kf*Lr)/M * ( -u(T1) + u(T3) )      ; ...
      Ki/(2*M) * ( u(T1) - u(T2) + u(T3) - u(T4) )            ];

if( nargout >= 3 )
  dfdx = [  0  0  0  1     0     0     0                                                                                       0  0       0         0         ; ...
            0  0  0  0     1     0     0                                                                                       0  0       0         0         ; ...
            0  0  0  0     0     1     0                                                                                       0  0       0         0         ; ...
            0  0  0  -b/m  0     0     0                                           (Kf/m)*cos(x(qphi))*sum(u)                  0  0       0         0         ; ...
            0  0  0  0     -b/m  0     -(Kf/m)*cos(x(qtheta))*cos(x(qphi))*sum(u)  (Kf/m)*sin(x(qtheta))*sin(x(qphi))* sum(u)  0  0       0         0         ; ...
            0  0  0  0     0     -b/m  -(Kf/m)*sin(x(qtheta))*cos(x(qphi))*sum(u)  -(Kf/m)*cos(x(qtheta))*sin(x(qphi))* sum(u) 0  0       0         0         ; ...   
            0  0  0  0     0     0     0                                                                                       0  1       0         0         ; ...
            0  0  0  0     0     0     0                                                                                       0  0       1         0         ; ...
            0  0  0  0     0     0     0                                                                                       0  0       0         1         ; ...
            0  0  0  0     0     0     0                                                                                       0  0       -x(vpsi)  -x(vphi)  ; ...
            0  0  0  0     0     0     0                                                                                       0  x(vpsi) 0         x(vtheta) ; ...
            0  0  0  0     0     0     0                                                                                       0  0       0         0         ];

  dfdu = [ 0                                  0                                  0                                  0                                  ; ...
           0                                  0                                  0                                  0                                  ; ...
           0                                  0                                  0                                  0                                  ; ...
           Kf/m*sin(x(qphi))                  Kf/m*sin(x(qphi))                  Kf/m*sin(x(qphi))                  Kf/m*sin(x(qphi))                  ; ...
           -Kf/m*sin(x(qtheta))*cos(x(qphi))  -Kf/m*sin(x(qtheta))*cos(x(qphi))  -Kf/m*sin(x(qtheta))*cos(x(qphi))  -Kf/m*sin(x(qtheta))*cos(x(qphi))  ; ...
           Kf/m*cos(x(qtheta))*cos(x(qphi))   Kf/m*cos(x(qtheta))*cos(x(qphi))   Kf/m*cos(x(qtheta))*cos(x(qphi))   Kf/m*cos(x(qtheta))*cos(x(qphi))   ; ...
           0                                  0                                  0                                  0                                  ; ...
           0                                  0                                  0                                  0                                  ; ...
           0                                  0                                  0                                  0                                  ; ...
           0                                  Kf*Lr/M                            0                                  -Kf*Lr/M                           ; ...
           -Kf*Lr/M                           0                                  Kf*Lr/M                            0                                  ; ...
           Ki/(2*M)                           -Ki/(2*M)                          Ki/(2*M)                           -Ki/(2*M)                          ];

end

